default_platform(:android)

platform :android do

  desc "Deploy a new version to the INTERNAL TESTING TRACK Google Play"
  lane :playstore do
    # gradle(
    #   tasks: ['clean', 'assembleRelease', 'bundleRelease'],
    # )
    sh("flutter build appbundle")
    upload_to_play_store(
      # Upload your app bundle to the Google Play Store
      aab: ENV["./build/app/outputs/bundle/release/app-release.aab"],
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      version_code: 1
    )
  end
end





